"""Handing a reproduction to a sandbox somebody already runs.

E2B, Daytona and dagger's container-use all solve "give an agent a disposable
environment", and each wants the recipe in its own shape. Integrating with them
would mean three API clients, three credential stores and three release
cadences to track, inside a tool whose entire value proposition is that it
contacts nothing.

So this emits their configuration files and stops. The user takes the file to
whichever sandbox they already pay for, and this project keeps its one moving
part -- the recipe -- instead of three.

That is also the more durable bet. The plan behind this work reads the sandbox
market as consolidating, with hyperscalers bundling and independents competing
on neutrality. A tool that speaks all their file formats and none of their APIs
survives that consolidation; a tool with three vendor SDKs pinned in its
dependency tree does not.

None of these is a claim of certification. Each format is written from public
documentation, marked as a draft, and carries the same review header as
everything else this project generates.
"""

from __future__ import annotations

import json
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from devrepro.reproduce.recipe import Reproduction

__all__ = ["ADAPTERS", "render_adapter"]

#: Sandbox to (filename, what the file is). The filename matters: each of these
#: tools looks for its config by name, and a correctly-shaped file with the
#: wrong name is invisible.
ADAPTERS: dict[str, tuple[str, str]] = {
    "e2b": ("e2b.Dockerfile", "E2B builds a custom template from a Dockerfile."),
    "daytona": (
        ".devcontainer/devcontainer.json",
        "Daytona reads a standard devcontainer; no bespoke format is needed.",
    ),
    "container-use": (
        "container-use.json",
        "dagger's container-use takes a base image and a setup command list.",
    ),
}

_NL = chr(10)


def render_adapter(name: str, recipe: Reproduction) -> tuple[str, str]:
    """`(filename, content)` for one sandbox, or raise for an unknown name.

    Returns the filename as well as the content because these tools discover
    their configuration by path. Handing somebody the right JSON with
    instructions to "save it somewhere" is handing them a file that does
    nothing.
    """
    from devrepro.reproduce.emit import render_devcontainer, render_dockerfile

    if name not in ADAPTERS:
        raise ValueError(f"unknown sandbox {name!r}: {', '.join(sorted(ADAPTERS))}")

    filename, _description = ADAPTERS[name]

    if name == "e2b":
        # E2B's template build is an ordinary Dockerfile, with one constraint
        # worth honouring: the template is built ahead of time and started per
        # session, so a CMD that runs the failing command would fire at build
        # time in some configurations. The failing command is left as a comment
        # for the session to run.
        body = render_dockerfile(recipe)
        if recipe.failing_command:
            body = body.replace(
                'CMD ["sh", "-c"',
                "# E2B starts sessions from this template rather than running it, so\n"
                "# the failing command belongs in the session, not in the image:\n"
                f"#   {recipe.failing_command}\n"
                '# CMD ["sh", "-c"',
            )
        return filename, body

    if name == "daytona":
        return filename, render_devcontainer(recipe)

    payload = {
        "//": (
            "Generated by devrepro - REVIEW REQUIRED. A draft written from public "
            "documentation, not a certified configuration."
        ),
        "image": recipe.image_reference,
        "setup": [step.command for step in recipe.steps if not step.command.startswith("COPY ")],
        "command": recipe.failing_command,
        "notes": [p.detail for p in recipe.preconditions],
    }
    if not recipe.pinned:
        payload["//pinning"] = (
            "The base image is a mutable tag; the sandbox can start a different "
            "container next month."
        )
    return filename, json.dumps(payload, indent=2) + _NL
