"""Rendering a reproduction into the formats people actually run.

One recipe, five outputs. The recipe is the model and these are views of it, so
a Dockerfile and a Nix flake describing the same failure cannot drift apart --
which they would if each were assembled from the scan independently.

Every one of them is **a file to read before running**. Each carries a header
saying what it was generated from, when, and on what machine, because the most
likely fate of a generated artefact is to be found in a wiki two years later
and followed without question.

The Nix and devcontainer outputs are deliberately interop rather than
competition. This project diagnoses environments; Nix manages them. Emitting a
flake somebody can take to a Nix-shaped team is more useful than pretending to
be a package manager, and it is the same reasoning behind not shipping a
toolchain installer.
"""

from __future__ import annotations

import json
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from devrepro.reproduce.recipe import Reproduction

__all__ = [
    "EMIT_FORMATS",
    "PROVENANCE_PREFIXES",
    "render_compose",
    "render_devcontainer",
    "render_dockerfile",
    "render_nix_flake",
    "render_repro_script",
    "strip_provenance",
]

#: What `devrepro reproduce --emit` accepts.
EMIT_FORMATS: tuple[str, ...] = ("dockerfile", "script", "compose", "devcontainer", "nix")

_NL = chr(10)

#: Header lines that record *when* rather than *what*. A recipe regenerated an
#: hour later differs on these and on nothing else, and a staleness check that
#: cannot tell those apart can only ever fail.
PROVENANCE_PREFIXES: tuple[str, ...] = ("Scanned at:", '"//generated-at"')


def strip_provenance(content: str) -> str:
    """The content of a recipe, with the timestamp lines removed.

    Used only for comparison. The timestamp stays in the emitted file, because
    a generated artefact with no date is the one that gets found in a wiki two
    years later and followed -- but a file that differs on every regeneration
    cannot be diffed, cannot be reviewed, and cannot be checked, which is the
    whole reason to emit a file rather than print a summary.

    So the rule is: a recipe is stale when what it *describes* has changed, not
    when it was regenerated.
    """
    return _NL.join(
        line
        for line in (content or "").splitlines()
        if not any(marker in line for marker in PROVENANCE_PREFIXES)
    )


def _header(recipe: Reproduction, comment: str = "#") -> list[str]:
    """The provenance block every emitted file carries.

    Not decoration. A generated file with no statement of where it came from
    gets found later and followed, and by then nobody can tell whether it still
    describes anything real.
    """
    lines = [
        f"{comment} Generated by devrepro {recipe.metadata.get('devrepro_version', '?')}.",
        f"{comment} Observed on: {recipe.metadata.get('observed_on', 'unknown')}",
        f"{comment} Scanned at:  {recipe.metadata.get('scanned_at', 'unknown')}",
        f"{comment} REVIEW BEFORE RUNNING. This is a draft of a reproduction, not a",
        f"{comment} verified one -- nothing here has been built or executed.",
    ]
    if not recipe.pinned:
        lines.append(f"{comment} NOT PINNED: the base image is referenced by a mutable tag, so")
        lines.append(f"{comment} this file can produce a different container next month. Re-run")
        lines.append(f"{comment} with a reachable container engine to resolve a digest.")
    if not recipe.reproduces:
        lines.append(f"{comment} NO FAILING COMMAND was supplied, so this sets up an environment")
        lines.append(f"{comment} and stops. Pass --failing-command to make it a reproduction:")
        lines.append(f"{comment} one that stops working when somebody fixes the cause.")
    for precondition in recipe.preconditions:
        lines.append(f"{comment} PRECONDITION [{precondition.kind}]: {precondition.detail}")
    return lines


def render_dockerfile(recipe: Reproduction) -> str:
    """A Dockerfile that ends by running the thing that failed.

    The failing command is the last line and it is *expected to fail*, which is
    why it is not a `RUN`: a `RUN` that fails aborts the build, and the build
    aborting is indistinguishable from the image being broken. It goes in `CMD`,
    so the container runs it and exits with its status -- and a person can tell
    a successful reproduction from a broken recipe.
    """
    lines = _header(recipe)
    lines.append("")
    lines.append(f"FROM {recipe.image_reference}")
    lines.append("WORKDIR /work")
    lines.append("")

    for step in recipe.steps:
        lines.append(f"# {step.reason}")
        if step.source:
            lines.append(f"# source: {step.source}")
        if step.command.startswith(("COPY ", "ADD ", "ENV ", "ARG ")):
            lines.append(step.command)
        else:
            lines.append(f"RUN {step.command}")
        lines.append("")

    if recipe.failing_command:
        lines.append("# The command that failed. CMD rather than RUN on purpose: a RUN")
        lines.append("# that fails aborts the build, which looks the same as a broken")
        lines.append("# recipe. This way the container exits with the failure's status.")
        if recipe.expected_symptom:
            lines.append(f"# Expected: {recipe.expected_symptom}")
        lines.append(f'CMD ["sh", "-c", {json.dumps(recipe.failing_command)}]')
    return _NL.join(lines) + _NL


def render_repro_script(recipe: Reproduction) -> str:
    """`repro.sh`: build it, run it, and say what the result means.

    Prints the interpretation rather than leaving it to an exit code, because
    the counter-intuitive part of a reproduction is that **success is failure**.
    A recipe that exits zero has not reproduced the bug, and somebody reading a
    green tick will draw the opposite conclusion from the right one.
    """
    lines = _header(recipe)
    lines.insert(0, "#!/usr/bin/env bash")
    lines.insert(1, "set -euo pipefail")
    lines.append("")
    lines.append('TAG="devrepro-repro:$(date +%s)"')
    lines.append('docker build -t "$TAG" -f Dockerfile.repro .')
    lines.append("")
    if recipe.failing_command:
        lines.append("set +e")
        lines.append('docker run --rm "$TAG"')
        lines.append("status=$?")
        lines.append("set -e")
        lines.append("")
        lines.append("if [ $status -eq 0 ]; then")
        lines.append('  echo "NOT REPRODUCED: the command succeeded in this container."')
        lines.append('  echo "Either the cause is not in the environment this recipe"')
        lines.append('  echo "captures, or it has already been fixed."')
        lines.append("  exit 1")
        lines.append("fi")
        lines.append('echo "REPRODUCED: exited $status, as reported."')
        if recipe.expected_symptom:
            lines.append(f'echo "Expected symptom: {recipe.expected_symptom}"')
        lines.append('echo "Note: check the failure matches. A different failure is not"')
        lines.append('echo "a reproduction, and is the usual way this wastes time."')
        lines.append("exit 0")
    else:
        lines.append('docker run --rm -it "$TAG" bash')
    return _NL.join(lines) + _NL


def render_compose(recipe: Reproduction, *, services: tuple[tuple[str, int], ...] = ()) -> str:
    """A compose file, for a failure that needs more than one container.

    `services` comes from what the project *declares* it needs -- ports in a
    policy, services in an existing compose file -- rather than from guessing.
    A reproduction that starts a Postgres nobody asked for is one more thing
    that can fail for the wrong reason.
    """
    lines = _header(recipe)
    lines.append("")
    lines.append("services:")
    lines.append("  repro:")
    lines.append("    build:")
    lines.append("      context: .")
    lines.append("      dockerfile: Dockerfile.repro")
    if services:
        lines.append("    depends_on:")
        for name, _port in services:
            lines.append(f"      - {name}")
    lines.append("")

    for name, port in services:
        lines.append(f"  {name}:")
        lines.append(f"    image: {name}:latest  # REVIEW: pin this before relying on it")
        lines.append("    ports:")
        lines.append(f'      - "{port}:{port}"')
        lines.append("")

    if not services:
        lines.append("# No additional services: nothing in this project declared any.")
        lines.append("# A reproduction that starts a database nobody asked for is one")
        lines.append("# more thing that can fail for the wrong reason.")
    return _NL.join(lines) + _NL


def render_devcontainer(recipe: Reproduction, *, features: dict[str, str] | None = None) -> str:
    """A devcontainer that opens *into* the failing environment.

    For the case where the reproduction is the starting point rather than the
    answer: somebody wants a shell in the environment where it breaks, not a
    container that exits with the failure.
    """
    payload: dict[str, object] = {
        "//": (
            "Generated by devrepro - REVIEW REQUIRED. Opens a shell in the environment "
            "where the failure was reported, rather than running the failure."
        ),
        "name": "devrepro-reproduction",
        "image": recipe.image_reference,
    }
    if not recipe.pinned:
        payload["//pinning"] = (
            "Referenced by a mutable tag. The same file can open a different container next month."
        )
    if features:
        payload["features"] = features
    if recipe.failing_command:
        payload["//failing-command"] = recipe.failing_command
    if recipe.preconditions:
        payload["//preconditions"] = [p.detail for p in recipe.preconditions]
    return json.dumps(payload, indent=2) + _NL


def render_nix_flake(recipe: Reproduction, *, packages: tuple[str, ...] = ()) -> str:
    """A flake draft, for teams whose environments are already Nix-shaped.

    Interop, not competition. This project diagnoses environments and Nix
    manages them; handing a Nix team a starting point is more useful than
    pretending to be a package manager, and it is the same reasoning behind not
    shipping a toolchain installer.

    Deliberately a `devShell` and not a build. A flake that claims to build the
    project would be claiming to have understood the build, which nothing here
    has done.
    """
    lines = _header(recipe)
    lines.append("")
    lines.append("{")
    lines.append(
        '  description = "Reproduction environment drafted by devrepro - REVIEW REQUIRED";'
    )
    lines.append("")
    lines.append('  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";')
    lines.append("  # REVIEW: `nixos-unstable` is a moving target. Pin it to a revision")
    lines.append("  # before relying on this, or the flake reproduces something else.")
    lines.append("")
    lines.append("  outputs = { self, nixpkgs }:")
    lines.append("    let")
    lines.append('      system = "x86_64-linux";')
    lines.append("      pkgs = nixpkgs.legacyPackages.${system};")
    lines.append("    in {")
    lines.append("      devShells.${system}.default = pkgs.mkShell {")
    if packages:
        listed = " ".join(f"pkgs.{name}" for name in packages)
        lines.append(f"        packages = [ {listed} ];")
    else:
        lines.append("        packages = [ ];  # nothing detected that maps to a nixpkgs name")
    lines.append("      };")
    lines.append("    };")
    lines.append("}")
    return _NL.join(lines) + _NL
