/**
 * A report for the browser suite to render.
 *
 * Without one, every route in the preview build showed the "Could not load
 * report" state -- `/api/report` has no proxy there and `./report.json` does
 * not exist -- and the route suite passed anyway, because it asserted that a
 * heading was visible and the error state has a heading. Thirty-two tests were
 * checking the same error page over and over and reporting it as coverage.
 *
 * Intercepting the fetch is better than committing a `public/report.json`,
 * which would ship a fabricated report inside every real build of the console.
 *
 * The fixture's *shape* is real -- generated by `devrepro scan` and then
 * trimmed -- because the point is to exercise the actual rendering paths. Its
 * *values* describe no one: version `0.0.0-fixture`, a fixed timestamp, and a
 * plausible Linux machine that does not exist.
 */
import type { Page } from '@playwright/test'

import report from './fixtures/report.json' with { type: 'json' }

export const FIXTURE_REPORT = report

/** Serve the fixture for every route the loader tries, in its own order. */
export async function serveReport(page: Page): Promise<void> {
  await page.route('**/api/report', (route) => route.fulfill({ json: report }))
  await page.route('**/report.json', (route) => route.fulfill({ json: report }))
}

/** Fail every report source, so the error state is what renders. */
export async function serveNoReport(page: Page): Promise<void> {
  await page.route('**/api/report', (route) => route.fulfill({ status: 404, body: '' }))
  await page.route('**/report.json', (route) => route.fulfill({ status: 404, body: '' }))
}
