"""Render `docs/RULES.md` from the rule catalogue.

The catalogue is the source; the page is a rendering of it. Committing a
generated file without a drift check is how documentation starts lying, so
`--check` fails when the committed page no longer matches what the catalogue
would produce -- the same contract `generate_schemas.py`,
`generate_landscape.py` and `capture_readme_example.py` already hold.

    python scripts/generate_rule_docs.py            # write
    python scripts/generate_rule_docs.py --check    # verify, for CI
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

TARGET = ROOT / "docs" / "RULES.md"
NL = chr(10)


def render() -> str:
    from devrepro.rules.catalog import all_rule_docs

    docs = all_rule_docs()
    lines = [
        "# Rule catalogue",
        "",
        "<!-- Generated by scripts/generate_rule_docs.py. Do not edit by hand; "
        "edit devrepro/rules/catalog.py and re-run it. -->",
        "",
        "> `devrepro explain <rule-id>` prints any one of these.",
        "> `devrepro rules --catalog` lists them all.",
        "",
        f"Every finding carries a rule id. There are **{len(docs)}** documented ids.",
        "",
        "Two shapes exist. Most are written out in full where they are emitted.",
        "Some are composed at runtime from a tool or ecosystem name:",
        "`multiple-installations` takes whichever tool was found twice, so it is",
        "valid for any tool name and the entries below are representative rather",
        "than exhaustive. `devrepro explain` resolves any prefix.",
        "",
    ]
    current: str | None = None
    for doc in docs:
        prefix = doc.rule_id.split("/", 1)[0]
        if prefix != current:
            current = prefix
            lines += ["", f"## `{prefix}/`", ""]
        lines += [
            f"### `{doc.rule_id}`",
            "",
            f"**{doc.title}**",
            "",
            f"*What it means.* {doc.means}",
            "",
            f"*Why it matters.* {doc.matters}",
            "",
            f"*How to fix it.* {doc.fix}",
            "",
        ]
    return NL.join(lines).rstrip() + NL


def main() -> int:
    rendered = render()
    check = "--check" in sys.argv
    existing = TARGET.read_text(encoding="utf-8") if TARGET.exists() else None

    if check:
        if existing == rendered:
            print("ok     docs/RULES.md matches the rule catalogue")
            return 0
        print(
            "drift  docs/RULES.md is stale; run: python scripts/generate_rule_docs.py",
            file=sys.stderr,
        )
        return 1

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(rendered, encoding="utf-8")
    print(f"wrote  docs/RULES.md ({rendered.count('### `')} rules)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
