"""Reviewable environment-config generators.

Generates DRAFT configuration files from explicit project requirements:
- ``.devrepro.toml`` policy draft;
- mise/``.tool-versions``-style tool version files;
- ``devcontainer.json`` starter.

Safety contract: generators NEVER overwrite an existing file. They return
the generated content plus a unified diff against any existing file so a
human can review before writing. Callers must pass ``allow_overwrite=True``
explicitly after review to write.
"""

from __future__ import annotations

import difflib
import json
from dataclasses import dataclass
from pathlib import Path

__all__ = [
    "DEFAULT_DEVCONTAINER_IMAGE",
    "MANAGED_RUNTIMES",
    "GeneratedFile",
    "features_for",
    "generate_devcontainer",
    "generate_devrepro_toml",
    "generate_tool_versions",
    "normalise_pin",
    "resolve_image_digest",
    "write_generated",
]

_NL = chr(10)


@dataclass(frozen=True)
class GeneratedFile:
    path: str
    content: str
    existed: bool
    diff: str  # empty when the file did not exist

    @property
    def requires_review(self) -> bool:
        return self.existed


def _diff_against(path: Path, new_content: str) -> tuple[bool, str]:
    if not path.exists():
        return False, ""
    old = path.read_text(encoding="utf-8", errors="replace").splitlines(keepends=True)
    diff = "".join(
        difflib.unified_diff(
            old,
            new_content.splitlines(keepends=True),
            fromfile=str(path),
            tofile=f"{path} (generated)",
        )
    )
    return True, diff


def generate_devrepro_toml(
    requirements: dict[str, str],
    required_env_names: tuple[str, ...] = (),
    require_docker: bool = False,
) -> str:
    """Draft a .devrepro.toml from detected requirements (name -> spec)."""
    lines = [
        "# Generated by devrepro-doctor - REVIEW BEFORE COMMITTING.",
        "# Draft derived from detected project requirements; adjust ranges to taste.",
        "",
        "[supported_os]",
        "windows = true",
        "linux = true",
        "macos = true",
        "",
    ]
    runtimes = {
        k: v
        for k, v in requirements.items()
        if k in {"python", "node", "go", "dotnet", "java", "ruby", "php", "rust"}
    }
    tools = {k: v for k, v in requirements.items() if k not in runtimes}
    lines.append("[required_runtimes]")
    lines.extend(f'{k} = "{runtimes[k]}"' for k in sorted(runtimes))
    lines.append("")
    lines.append("[required_tools]")
    lines.extend(f'{k} = "{tools[k]}"' for k in sorted(tools))
    if require_docker and "docker" not in tools:
        lines.append('docker = ">=24"')
    lines.append("")
    if required_env_names:
        lines.append("[required_env_names]")
        names = ", ".join(f'"{n}"' for n in required_env_names)
        lines.append(f"names = [{names}]")
        lines.append("")
    return _NL.join(lines)


#: Runtimes mise and asdf actually manage. A library dependency is not
#: installable by a version manager, and listing one produces a file that
#: errors on load rather than a helpful suggestion.
MANAGED_RUNTIMES = frozenset(
    {
        "python",
        "node",
        "go",
        "java",
        "rust",
        "ruby",
        "php",
        "dotnet",
        "deno",
        "bun",
        "erlang",
        "elixir",
        "kotlin",
        "scala",
        "swift",
        "terraform",
        "kubectl",
        "helm",
        "awscli",
        "zig",
        "julia",
        "perl",
    }
)


def normalise_pin(spec: str) -> str | None:
    """A version a tool manager will accept, or None if there isn't one.

    Manifest specs carry things a version manager cannot use: PEP 508
    environment markers (`2.0; python_version < "3.11"`), comma ranges, and
    quotes that survived from the source document. `""3.12""` -- quotes already
    present, then quoted again -- is not valid TOML, which is what this file
    used to emit.
    """
    if not spec:
        return None
    # An environment marker applies to a dependency, not to a runtime version.
    spec = spec.split(";", 1)[0]
    # A range cannot be installed; take the lower bound, which is the version
    # the project has actually said it needs.
    spec = spec.split(",", 1)[0]
    spec = spec.strip().strip("\"'").lstrip("^~>=< ").strip()
    if not spec or spec == "*":
        return None
    # Reject anything left that is not a version: wildcards, urls, markers.
    if not spec[0].isdigit():
        return None
    return spec


def _managed_pins(requirements: dict[str, str]) -> dict[str, str]:
    """Requirements a version manager can act on, normalised."""
    pins: dict[str, str] = {}
    for name, spec in requirements.items():
        # `ci:python` records what a workflow declares. It is a useful
        # requirement and not a tool to install.
        if ":" in name or name not in MANAGED_RUNTIMES:
            continue
        version = normalise_pin(spec)
        if version is not None:
            pins[name] = version
    return pins


def generate_tool_versions(requirements: dict[str, str], style: str = "mise") -> str:
    """Generate a .mise.toml or .tool-versions draft from pinned versions."""
    pins = _managed_pins(requirements)

    if style == "asdf":
        header = [
            "# Generated by devrepro-doctor - REVIEW BEFORE COMMITTING.",
        ]
        body = [f"{k} {v}" for k, v in sorted(pins.items())]
        if not body:
            header.append("# No managed runtime versions were detected to pin.")
        return _NL.join(header + body) + _NL

    lines = [
        "# Generated by devrepro-doctor - REVIEW BEFORE COMMITTING.",
        "# NOTE: this pins versions but does NOT guarantee full reproducibility;",
        "# use Nix/devenv/Devbox when bit-for-bit environments are required.",
        "[tools]",
    ]
    if not pins:
        lines.append("# No managed runtime versions were detected to pin.")
    lines.extend(f'{k} = "{v}"' for k, v in sorted(pins.items()))
    return _NL.join(lines) + _NL


#: Devcontainer features for the runtimes this project detects. The keys are
#: the names `detect_requirements` reports; the values are the published
#: feature images.
_DEVCONTAINER_FEATURES = {
    "node": "ghcr.io/devcontainers/features/node:1",
    "python": "ghcr.io/devcontainers/features/python:1",
    "go": "ghcr.io/devcontainers/features/go:1",
    "java": "ghcr.io/devcontainers/features/java:1",
    "dotnet": "ghcr.io/devcontainers/features/dotnet:2",
    "rust": "ghcr.io/devcontainers/features/rust:1",
    "ruby": "ghcr.io/devcontainers/features/ruby:1",
    "php": "ghcr.io/devcontainers/features/php:1",
    "docker": "ghcr.io/devcontainers/features/docker-in-docker:2",
}

DEFAULT_DEVCONTAINER_IMAGE = "mcr.microsoft.com/devcontainers/base:ubuntu-24.04"


def features_for(requirements: dict[str, str]) -> dict[str, dict[str, str]]:
    """Devcontainer features implied by what the project declares.

    A devcontainer that installs nothing the project needs is a container the
    reader has to finish by hand, which is most of the reason generated
    devcontainers get deleted. The declared version is carried through, so the
    container starts on the range the manifest already asks for.
    """
    features: dict[str, dict[str, str]] = {}
    for name, spec in sorted(requirements.items()):
        feature = _DEVCONTAINER_FEATURES.get(name)
        if feature is None:
            continue
        version = spec.lstrip("^~>=< ").split(",")[0].strip() or "latest"
        features[feature] = {"version": version}
    return features


def resolve_image_digest(image: str, runner: object | None = None) -> str | None:
    """Resolve a tag to an immutable ``name@sha256:...`` reference.

    Uses the local docker CLI rather than an HTTP call to the registry: the
    user's credentials, mirrors and proxy settings already live there, and
    reimplementing registry auth to save a subprocess would be a poor trade.

    Returns None when docker is absent or the image cannot be resolved --
    pinning is an improvement on the output, not a precondition for producing
    it.
    """
    from devrepro.core.runner import SubprocessRunner

    runner = runner or SubprocessRunner()
    result = runner.run(  # type: ignore[attr-defined]
        ("docker", "buildx", "imagetools", "inspect", image, "--format", "{{.Manifest.Digest}}"),
        timeout=60,
    )
    digest = (result.stdout or "").strip()
    if result.ok and digest.startswith("sha256:"):
        return f"{image.split('@', maxsplit=1)[0].split(':', maxsplit=1)[0]}@{digest}"

    # Older docker without buildx imagetools; `manifest inspect` needs
    # experimental features but is widely available.
    result = runner.run(("docker", "manifest", "inspect", "--verbose", image), timeout=60)  # type: ignore[attr-defined]
    if result.ok:
        import json as _json

        try:
            payload = _json.loads(result.stdout)
        except ValueError:
            return None
        entry = payload[0] if isinstance(payload, list) and payload else payload
        digest = (entry or {}).get("Descriptor", {}).get("digest", "")
        if digest.startswith("sha256:"):
            return f"{image.split('@', maxsplit=1)[0].split(':', maxsplit=1)[0]}@{digest}"
    return None


def generate_devcontainer(
    image: str = DEFAULT_DEVCONTAINER_IMAGE,
    features: tuple[str, ...] = (),
    forward_ports: tuple[int, ...] = (),
    *,
    requirements: dict[str, str] | None = None,
    digest: str | None = None,
) -> str:
    """Draft a devcontainer.json; clearly marked as generated.

    ``digest`` replaces the tag with an immutable reference. Without it the
    file carries a comment saying so, because a tag is a moving target and a
    reproducibility artefact that silently changes is worse than one that
    admits it cannot promise anything.
    """
    resolved = digest or image
    payload: dict[str, object] = {
        "//": "Generated by devrepro-doctor - REVIEW REQUIRED before use.",
        "name": "project-devcontainer",
        "image": resolved,
    }
    if digest is None:
        payload["//pinning"] = (
            "This image is referenced by TAG, which is mutable: the same file can "
            "produce a different container next month. Re-run with --pin to "
            "resolve it to an immutable sha256 digest."
        )

    combined: dict[str, object] = {}
    if requirements:
        combined.update(features_for(requirements))
    combined.update(dict.fromkeys(features, "latest"))
    if combined:
        payload["features"] = combined
    if forward_ports:
        payload["forwardPorts"] = list(forward_ports)
    return json.dumps(payload, indent=2) + _NL


def write_generated(
    target: Path | str, content: str, *, allow_overwrite: bool = False
) -> GeneratedFile:
    """Write generated content, refusing to clobber without explicit approval."""
    target = Path(target)
    existed, diff = _diff_against(target, content)
    if existed and not allow_overwrite:
        return GeneratedFile(str(target), content, existed=True, diff=diff)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8")
    return GeneratedFile(str(target), content, existed=existed, diff=diff)
