"""Reviewable environment-config generators.

Generates DRAFT configuration files from explicit project requirements:
- ``.devrepro.toml`` policy draft;
- mise/``.tool-versions``-style tool version files;
- ``devcontainer.json`` starter.

Safety contract: generators NEVER overwrite an existing file. They return
the generated content plus a unified diff against any existing file so a
human can review before writing. Callers must pass ``allow_overwrite=True``
explicitly after review to write.
"""

from __future__ import annotations

import difflib
import json
from dataclasses import dataclass
from pathlib import Path

__all__ = [
    "GeneratedFile",
    "generate_devcontainer",
    "generate_devrepro_toml",
    "generate_tool_versions",
    "write_generated",
]

_NL = chr(10)


@dataclass(frozen=True)
class GeneratedFile:
    path: str
    content: str
    existed: bool
    diff: str  # empty when the file did not exist

    @property
    def requires_review(self) -> bool:
        return self.existed


def _diff_against(path: Path, new_content: str) -> tuple[bool, str]:
    if not path.exists():
        return False, ""
    old = path.read_text(encoding="utf-8", errors="replace").splitlines(keepends=True)
    diff = "".join(
        difflib.unified_diff(
            old,
            new_content.splitlines(keepends=True),
            fromfile=str(path),
            tofile=f"{path} (generated)",
        )
    )
    return True, diff


def generate_devrepro_toml(
    requirements: dict[str, str],
    required_env_names: tuple[str, ...] = (),
    require_docker: bool = False,
) -> str:
    """Draft a .devrepro.toml from detected requirements (name -> spec)."""
    lines = [
        "# Generated by devrepro-doctor - REVIEW BEFORE COMMITTING.",
        "# Draft derived from detected project requirements; adjust ranges to taste.",
        "",
        "[supported_os]",
        "windows = true",
        "linux = true",
        "macos = true",
        "",
    ]
    runtimes = {
        k: v
        for k, v in requirements.items()
        if k in {"python", "node", "go", "dotnet", "java", "ruby", "php", "rust"}
    }
    tools = {k: v for k, v in requirements.items() if k not in runtimes}
    lines.append("[required_runtimes]")
    lines.extend(f'{k} = "{runtimes[k]}"' for k in sorted(runtimes))
    lines.append("")
    lines.append("[required_tools]")
    lines.extend(f'{k} = "{tools[k]}"' for k in sorted(tools))
    if require_docker and "docker" not in tools:
        lines.append('docker = ">=24"')
    lines.append("")
    if required_env_names:
        lines.append("[required_env_names]")
        names = ", ".join(f'"{n}"' for n in required_env_names)
        lines.append(f"names = [{names}]")
        lines.append("")
    return _NL.join(lines)


def generate_tool_versions(requirements: dict[str, str], style: str = "mise") -> str:
    """Generate a .mise.toml or .tool-versions draft from pinned versions."""
    pins = {k: v.lstrip("^~>=< ") for k, v in requirements.items() if v not in ("*", "")}
    if style == "asdf":
        return "".join(f"{k} {v}{_NL}" for k, v in sorted(pins.items()))
    # mise TOML
    lines = [
        "# Generated by devrepro-doctor - REVIEW BEFORE COMMITTING.",
        "# NOTE: this pins versions but does NOT guarantee full reproducibility;",
        "# use Nix/devenv/Devbox when bit-for-bit environments are required.",
        "[tools]",
    ]
    lines.extend(f'{k} = "{v}"' for k, v in sorted(pins.items()))
    return _NL.join(lines) + _NL


def generate_devcontainer(
    image: str = "mcr.microsoft.com/devcontainers/base:ubuntu-24.04",
    features: tuple[str, ...] = (),
    forward_ports: tuple[int, ...] = (),
) -> str:
    """Draft a minimal devcontainer.json; clearly marked as generated."""
    payload: dict[str, object] = {
        "//": "Generated by devrepro-doctor - REVIEW REQUIRED before use.",
        "name": "project-devcontainer",
        "image": image,
    }
    if features:
        payload["features"] = dict.fromkeys(features, "latest")
    if forward_ports:
        payload["forwardPorts"] = list(forward_ports)
    return json.dumps(payload, indent=2) + _NL


def write_generated(
    target: Path | str, content: str, *, allow_overwrite: bool = False
) -> GeneratedFile:
    """Write generated content, refusing to clobber without explicit approval."""
    target = Path(target)
    existed, diff = _diff_against(target, content)
    if existed and not allow_overwrite:
        return GeneratedFile(str(target), content, existed=True, diff=diff)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8")
    return GeneratedFile(str(target), content, existed=existed, diff=diff)
