"""Reporting into the MDM a company already runs, without becoming one.

Jamf, Intune and Kandji all have the same two extension points: run a script,
read what it prints. That is the whole integration surface anybody needs here,
and it is the reason this is a script generator rather than three API clients.

The alternative -- talking to each vendor's Graph or Classic API -- would mean
credentials, tenant configuration, three release cadences and a service account
with fleet-wide read access, all inside a tool whose entire proposition is that
it holds nothing and contacts nothing. And it would duplicate the fleet server
this project already ships for teams that want central reporting.

**What each script reports is a verdict, not an inventory.** An MDM already
knows the machine's OS, serial and installed applications; it does not know
whether the machine can build the company's software, which is the one thing
this can tell it. Sending a toolchain inventory into an MDM would put a
developer's local software list into a system that HR and IT security query --
a different audience from the one that data was collected for, and the sort of
scope creep that gets a tool banned.

So each script emits one short string. Jamf's extension attributes take a
single value; Intune's compliance scripts take an exit code and a line of
output; Kandji reads stdout from a custom script. All three are satisfied by a
verdict and a blocker count, and none of them receives a path, a version list or
a username.
"""

from __future__ import annotations

__all__ = ["MDM_PLATFORMS", "render_mdm_script"]

#: Platform to (filename, what the vendor does with it).
MDM_PLATFORMS: dict[str, tuple[str, str]] = {
    "jamf": (
        "devrepro-extension-attribute.sh",
        "Jamf extension attribute: one value per machine, queryable in a smart group.",
    ),
    "intune": (
        "devrepro-compliance.ps1",
        "Intune custom compliance: exit code plus one line of JSON output.",
    ),
    "kandji": (
        "devrepro-custom-script.sh",
        "Kandji custom script: stdout is captured and shown per device.",
    ),
}

_NL = chr(10)

_PREAMBLE = (
    "Generated by devrepro. REVIEW BEFORE DEPLOYING: this runs on every managed",
    "machine on your MDM's schedule.",
    "",
    "It reports a VERDICT and a blocker count -- nothing else. No paths, no",
    "version inventory, no username. Your MDM already knows the machine; what it",
    "does not know is whether that machine can build your software, and that is",
    "the only thing this adds. Sending an inventory here would put a developer's",
    "local software list in front of an audience it was not collected for.",
)


def render_mdm_script(platform: str, *, repo_path: str = "/opt/company/repo") -> tuple[str, str]:
    """`(filename, content)` for one MDM's extension point.

    Returns the filename because each vendor discovers scripts differently and a
    correctly-written script under the wrong name is one nobody notices is not
    running.
    """
    if platform not in MDM_PLATFORMS:
        raise ValueError(f"unknown MDM {platform!r}: {', '.join(sorted(MDM_PLATFORMS))}")

    filename, _description = MDM_PLATFORMS[platform]

    if platform == "intune":
        comment = _NL.join(f"# {line}".rstrip() for line in _PREAMBLE)
        body = f"""{comment}

# Intune custom compliance expects a single line of JSON on stdout whose keys
# match the detection rules you upload alongside this script.

$ErrorActionPreference = "Stop"
$repo = "{repo_path}"

try {{
    $output = & devrepro preflight --json 2>$null | ConvertFrom-Json
    $verdict = $output.verdict
    $blockers = @($output.blockers).Count
}} catch {{
    # devrepro absent or the scan failed. Reported as unknown rather than
    # compliant: a check that reports success when it could not run is worse
    # than one that is missing.
    $verdict = "UNKNOWN"
    $blockers = -1
}}

@{{ DevReproVerdict = $verdict; DevReproBlockers = $blockers }} | ConvertTo-Json -Compress
"""
        return filename, body

    comment = _NL.join(f"# {line}".rstrip() for line in _PREAMBLE)
    # Not indented: this one runs at the top level, and the two leading spaces
    # the fallback needs inside its `if` looked like a stray block in the
    # generated file.
    result_line = (
        'echo "<result>$verdict ($blockers blocker(s))</result>"'
        if platform == "jamf"
        else 'echo "$verdict ($blockers blocker(s))"'
    )
    fallback_line = (
        '  echo "<result>UNKNOWN (devrepro not installed)</result>"'
        if platform == "jamf"
        else '  echo "UNKNOWN (devrepro not installed)"'
    )

    return (
        filename,
        f"""#!/bin/bash
{comment}

set -uo pipefail
REPO="{repo_path}"

# Pulled out of the pipeline: the escaping is dense enough that inline it
# reads as noise, and it is the one line here anybody will need to adjust.
VERDICT_RE='s/.*"verdict"[[:space:]]*:[[:space:]]*"\\([^"]*\\)".*/\\1/p'

if ! command -v devrepro >/dev/null 2>&1; then
{fallback_line}
  # Reported as unknown, not as compliant. A check that reports success when it
  # could not run is worse than one that is missing, because it is believed.
  exit 0
fi

cd "$REPO" 2>/dev/null || true
json="$(devrepro preflight --json 2>/dev/null || true)"

verdict="$(printf '%s' "$json" | sed -n "$VERDICT_RE")"
blockers="$(printf '%s' "$json" | grep -o '"[a-z0-9-]*/[a-z0-9-]*"' | wc -l | tr -d ' ')"
[ -n "$verdict" ] || verdict="UNKNOWN"

{result_line}
exit 0
""",
    )
