import { useState } from 'react'
import { t } from '../i18n'

import type { Finding, ScanReport } from '../types'

/**
 * Exporting a view, and the one format deliberately not offered.
 *
 * **Markdown** is the format that matters. The reason somebody exports a
 * diagnostic is to paste it into an issue, a pull request or a chat message,
 * and all three of those render Markdown and none of them render a PNG usefully
 * — an image of a table is a table nobody can search, quote or diff.
 *
 * **PDF** comes from the browser's own print-to-PDF, driven by a print
 * stylesheet. Nothing is bundled for it. A PDF library is several hundred
 * kilobytes to reproduce, worse, something every browser already does — and it
 * would have to re-implement the theme, the fonts and the page breaks.
 *
 * **PNG is not offered.** Rendering the DOM to a canvas needs a library
 * (`html2canvas` and friends are ~200 KB), reproduces the layout approximately
 * rather than exactly, and produces the least useful artefact of the three:
 * text nobody can select, in a file nobody can diff. If you want a picture, the
 * operating system's screenshot key already makes a better one than any library
 * would.
 *
 * Everything here runs in the page. No upload, no service, and the exported
 * text is the same sanitized report the view is rendering.
 */

function severityCounts(findings: Finding[]): Record<string, number> {
  const counts: Record<string, number> = {}
  for (const finding of findings) counts[finding.state] = (counts[finding.state] ?? 0) + 1
  return counts
}

/**
 * A report as Markdown, in the shape an issue comment wants.
 *
 * Blockers first and capped, because the reason to paste this somewhere is the
 * thing that is broken — and a comment that opens with forty INFO rows is one
 * nobody scrolls past.
 */
export function reportToMarkdown(report: ScanReport, { limit = 25 }: { limit?: number } = {}): string {
  const findings = report.findings ?? []
  const rank: Record<string, number> = { BLOCKED: 0, ERROR: 1, WARN: 2, UNKNOWN: 3, INFO: 4, PASS: 5 }
  const ordered = [...findings].sort(
    (a, b) => (rank[a.state] ?? 9) - (rank[b.state] ?? 9) || a.rule_id.localeCompare(b.rule_id),
  )
  const shown = ordered.slice(0, limit)
  const counts = severityCounts(findings)

  const lines: string[] = [
    '## devrepro scan',
    '',
    `- **Machine:** ${report.platform?.os_name ?? '?'} ${report.platform?.os_version ?? ''} (${report.platform?.arch ?? '?'})`,
    `- **Scanned:** ${report.created_at ?? 'unknown'}`,
    `- **devrepro:** ${report.devrepro_version ?? 'unknown'}`,
    `- **Findings:** ${Object.entries(counts).map(([state, n]) => `${n} ${state}`).join(', ') || 'none'}`,
    '',
  ]

  if (shown.length > 0) {
    lines.push('| State | Rule | Summary |', '| --- | --- | --- |')
    for (const finding of shown) {
      // Pipes inside a cell end it, and a rule summary can legitimately carry
      // one — a shell fragment, a PATH. Escaped rather than stripped, so the
      // text still reads correctly.
      const summary = (finding.summary ?? '').replace(/\|/g, '\\|')
      lines.push(`| ${finding.state} | \`${finding.rule_id}\` | ${summary} |`)
    }
    if (ordered.length > shown.length) {
      lines.push('', `_…and ${ordered.length - shown.length} more. Run \`devrepro doctor\` for the full report._`)
    }
  } else {
    lines.push('No findings.')
  }

  lines.push('', '_Generated by devrepro. Paths and secrets are redacted before a report is written._')
  return lines.join('\n')
}

/**
 * Copy-to-clipboard, print, and an explanation of what is missing.
 *
 * The button that is not here is as deliberate as the two that are, so the
 * component says so rather than leaving somebody hunting for it.
 */
export function ExportBar({ report }: { report: ScanReport }) {
  const [copied, setCopied] = useState(false)

  async function copyMarkdown() {
    try {
      await navigator.clipboard.writeText(reportToMarkdown(report))
      setCopied(true)
      window.setTimeout(() => setCopied(false), 2000)
    } catch {
      // A clipboard write can be refused — an insecure origin, a permission
      // policy, a browser that only allows it inside a user gesture it did not
      // recognise. Failing silently would leave somebody clicking a button that
      // does nothing.
      setCopied(false)
      window.alert('The browser refused clipboard access. Select the report text and copy it manually.')
    }
  }

  return (
    <div className="export-bar">
      <button type="button" className="btn" onClick={copyMarkdown}>
        {copied ? `✓ ${t('action.copied')}` : t('action.copyMarkdown')}
      </button>
      <button type="button" className="btn" onClick={() => window.print()}>
        {t('action.print')}
      </button>
      <span className="muted export-note">
        Markdown, because the reason to export a diagnostic is to paste it into an issue — and an
        image of a table is a table nobody can search or quote. PDF comes from your browser's own
        print dialogue rather than a bundled library.
      </span>
    </div>
  )
}
